### ISSUE TITLE
How do I use the files to translate the game?

### ISSUE THREAD

**Issue by Blue7x** [TwinDragon/cornelica-translation#60]
Tittle

**Comment by Antielfi** [comment]
I update the repository for a simple way. You need to download the game and unzip it making sure to have the Japanase Languagepack install so you don't ruin the gamefile name.

# -----ALWAYS DO A BACKUP OF THE ORIGINAL-----

After that you simply need to Copy-Pasta and override the original file.
Going on the main page of the project, click Clone or Download -> Download ZIP
Unzip and go to the Cornelica sub-folder.
You need to copy the 3 folder in the right position:

- data -> /yourgamefolder/www/data
- js -> /yourgamefolder/www/js    (there is a subfolder called plugin in both location to override)
- scenario -> /yourgamefolder/scenario (MAKE a backup and delete the old folder

We edit the JS file for enabling the game to read the .txt instead of .sl
In the final release we will fix that, for now is more handly do it this way for TL

The img workaround is not publish here for security reason.

I will leave open the Issue for problem or more question

**Comment by TwinDragon** [comment]
Even if its closed, one can still comment in here. Unless I lock it, but no real need to. I added instructions based on @Antielfi just above to the main README.
