### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by Surothedeath** [TwinDragon/cornelica-translation#61]
i wonder is somone have translate the nun sceen

**Comment by Antielfi** [comment]
We are in the mud for the remaining scenes due to the increasing difficulty of translations. The remaining scenes can not be translated "forcibly" like the others but require ... attentions and a good knowledge. I think I speak on behalf of all those who contributed when I say we can not wait to see this project finished.

The door remains open for any other volunteer who is able to lend a hand or even a straight on how to proceed with the remaining scenes.
As always I leave complete willingness to help where some clarification may be needed.

I hope in the next weeks to be able to take up the texts and try again to translate them in the light of new research ...
